/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatePicker: typeof import('primevue/datepicker')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
