/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    FilterDrawer: typeof import('./src/components/FilterDrawer.vue')['default']
    HistDateRangeSelector: typeof import('./src/components/HistDateRangeSelector.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    OverlayBadge: typeof import('primevue/overlaybadge')['default']
    Panel: typeof import('primevue/panel')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultItem: typeof import('./src/components/SearchResultItem.vue')['default']
    SearchResultList: typeof import('./src/components/SearchResultList.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    StatusPopup: typeof import('./src/components/StatusPopup.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}

// For TSX support
declare global {
  const AppToolbar: typeof import('./src/components/AppToolbar.vue')['default']
  const Badge: typeof import('primevue/badge')['default']
  const Button: typeof import('primevue/button')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const Divider: typeof import('primevue/divider')['default']
  const Drawer: typeof import('primevue/drawer')['default']
  const FilterDrawer: typeof import('./src/components/FilterDrawer.vue')['default']
  const HistDateRangeSelector: typeof import('./src/components/HistDateRangeSelector.vue')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Menu: typeof import('primevue/menu')['default']
  const NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
  const OverlayBadge: typeof import('primevue/overlaybadge')['default']
  const Panel: typeof import('primevue/panel')['default']
  const ProgressBar: typeof import('primevue/progressbar')['default']
  const ProgressSpinner: typeof import('primevue/progressspinner')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SearchResultItem: typeof import('./src/components/SearchResultItem.vue')['default']
  const SearchResultList: typeof import('./src/components/SearchResultList.vue')['default']
  const Skeleton: typeof import('primevue/skeleton')['default']
  const StatusPopup: typeof import('./src/components/StatusPopup.vue')['default']
  const Tag: typeof import('primevue/tag')['default']
  const ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  const Toolbar: typeof import('primevue/toolbar')['default']
}